### ISSUE TITLE
Detect portable VLC

### ISSUE THREAD

**Issue by mrghosh** [feross/vlc-command#7]
Please see this [issue](https://github.com/webtorrent/webtorrent-cli/issues/63) for details.

It seems that in Windows platform, vlc-command gets the VLC installation path from the registry. Is there any way to make it work if I add the VLC location to the environment variable 'Path'? I actually don't want to install VLC. I just want to use the portable VLC.

Is it possible to add code to use `where vlc` command output, if install directory is unavailable from the registry? Thank you :)

**Comment by feross** [comment]
I don't have any immediate plans to work on this issue, so I'm going to close it. If you (or anyone else) wants to tackle it, I'll happily accept a PR!

I just don't have time prioritize an issue that is an edge case like this. If it's important to you, please send a PR.
